spring.application.name=databasename
spring.datasource.username=username
spring.datasource.password=password
spring.datasource.url=url

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false